import type { TrackItem, VideoInfo } from "@/common/types";

/**
 * Copy of `tracks` with the favorite languages first, in the order of
 * `favoriteLangCodes`; the remaining tracks keep their relative order.
 */
export function sortByFavorite<T extends TrackItem>(
    tracks: readonly T[],
    favoriteLangCodes: readonly string[],
): T[] {
    const rank = (track: T) => {
        const index = favoriteLangCodes.indexOf(track.languageCode);
        return index === -1 ? Infinity : index;
    };
    return [...tracks].sort((a, b) => rank(a) - rank(b));
}

/**
 * The tracks worth showing: human captions and dubs, without auto-generated
 * captions and the original audio.
 */
export function badgeTracks(info: VideoInfo): VideoInfo {
    return {
        captions: info.captions.filter((t) => !t.isAutoGenerated),
        audioTracks: info.audioTracks.filter((t) => !t.isOriginal),
    };
}

/**
 * Whether the video has a human caption or a dub in one of the favorite
 * languages - the same rule the badges highlight. Applies badgeTracks()
 * itself, although embed.ts hands it info that is filtered already, so the
 * answer is right whatever a caller passes.
 */
export function hasFavoriteTrack(
    info: VideoInfo,
    favoriteLangCodes: readonly string[],
): boolean {
    const { captions, audioTracks } = badgeTracks(info);
    return [...captions, ...audioTracks].some((t) =>
        favoriteLangCodes.includes(t.languageCode),
    );
}
