import type { VideoInfo } from "@/common/types";
import { IDBFactory } from "fake-indexeddb";
import "fake-indexeddb/auto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const DB_NAME = "subpeek-video-cache";
const STORE = "videoInfo";

const info: VideoInfo = {
    captions: [{ languageCode: "en", name: "English", isAutoGenerated: false }],
    audioTracks: [{ languageCode: "ja", name: "Japanese", isOriginal: false }],
};

// The cache singleton keeps its database connection, so each test gets a
// fresh module on top of an empty IndexedDB and a controllable clock.
async function loadCache() {
    vi.resetModules();
    return import("@/common/cache");
}

beforeEach(() => {
    vi.stubGlobal("indexedDB", new IDBFactory());
    vi.useFakeTimers({ toFake: ["Date"] });
    vi.setSystemTime(new Date("2026-09-17T12:00:00Z"));
});

afterEach(() => {
    vi.useRealTimers();
    vi.unstubAllGlobals();
});

describe("videoCache", () => {
    it("returns what was stored while it is fresh", async () => {
        const { videoCache } = await loadCache();

        await videoCache.set("abc", info);

        expect(await videoCache.get("abc")).toEqual(info);
        expect(await videoCache.get("zzz")).toBeNull();
    });

    it("hides an entry once it is older than the TTL", async () => {
        const { videoCache, CACHE_TTL_SECONDS } = await loadCache();
        await videoCache.set("abc", info);

        vi.setSystemTime(Date.now() + (CACHE_TTL_SECONDS + 1) * 1000);

        expect(await videoCache.get("abc")).toBeNull();
    });

    it("sweeps expired entries and keeps the fresh ones", async () => {
        const { videoCache, CACHE_TTL_SECONDS } = await loadCache();
        await videoCache.set("old", info);
        vi.setSystemTime(Date.now() + (CACHE_TTL_SECONDS + 1) * 1000);
        await videoCache.set("new", info);

        await videoCache.cleanExpired();

        expect(await countEntries()).toBe(1);
        expect(await videoCache.get("new")).toEqual(info);
    });

    it("drops entries written under the previous schema version", async () => {
        await seedVersion1({
            videoId: "abc",
            data: { captions: [], audioTracks: [] },
            timestamp: Date.now() / 1000,
        });
        const { videoCache } = await loadCache();

        expect(await videoCache.get("abc")).toBeNull();

        await videoCache.set("abc", info);
        expect(await videoCache.get("abc")).toEqual(info);
    });
});

/** IndexedDB reports failures through a nullable `error`; always reject with an Error. */
const failure = (error: DOMException | null) =>
    error ?? new Error("IndexedDB request failed");

/** Creates the database the way version 1 of the extension did. */
function seedVersion1(entry: unknown): Promise<void> {
    return new Promise((resolve, reject) => {
        const request = indexedDB.open(DB_NAME, 1);
        request.onupgradeneeded = () => {
            const store = request.result.createObjectStore(STORE, {
                keyPath: "videoId",
            });
            store.createIndex("timestamp", "timestamp");
        };
        request.onerror = () => reject(failure(request.error));
        request.onsuccess = () => {
            const db = request.result;
            const tx = db.transaction(STORE, "readwrite");
            tx.objectStore(STORE).put(entry);
            tx.oncomplete = () => {
                db.close();
                resolve();
            };
            tx.onerror = () => reject(failure(tx.error));
        };
    });
}

function countEntries(): Promise<number> {
    return new Promise((resolve, reject) => {
        const request = indexedDB.open(DB_NAME);
        request.onerror = () => reject(failure(request.error));
        request.onsuccess = () => {
            const db = request.result;
            const count = db.transaction(STORE).objectStore(STORE).count();
            count.onsuccess = () => {
                db.close();
                resolve(count.result);
            };
            count.onerror = () => reject(failure(count.error));
        };
    });
}
