import type { VideoInfo } from "@/common/types";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fakeBrowser } from "wxt/testing/fake-browser";

const mocks = vi.hoisted(() => ({
    resolveVideoInfo:
        vi.fn<
            (
                url: string,
                stillNeeded?: () => boolean,
            ) => Promise<VideoInfo | null>
        >(),
}));
vi.mock("@/entrypoints/content/youtube/api", () => ({
    resolveVideoInfo: mocks.resolveVideoInfo,
}));

const info: VideoInfo = {
    captions: [
        { languageCode: "en", name: "English", isAutoGenerated: false },
        { languageCode: "fr", name: "French", isAutoGenerated: false },
        { languageCode: "de", name: "German", isAutoGenerated: false },
        { languageCode: "es", name: "Spanish (auto)", isAutoGenerated: true },
    ],
    audioTracks: [
        { languageCode: "en", name: "English original", isOriginal: true },
        { languageCode: "ja", name: "Japanese", isOriginal: false },
    ],
};

const VIDEO_URL = "https://www.youtube.com/watch?v=abc";
const flush = () => new Promise((resolve) => setTimeout(resolve, 0));

// Fresh modules per test: the settings wrapper caches storage in memory.
// main.ts subscribes rerenderEmbeds() to the favorites in start(); do the same
// here so a storage change redraws the mounted embeds.
async function loadEmbed(favorites: string[]) {
    fakeBrowser.reset();
    await fakeBrowser.storage.local.set({ "SETTINGS:langCodes": favorites });
    document.body.innerHTML = "";
    vi.resetModules();
    const { Settings } = await import("@/common/settings");
    await Settings.ready();
    const embed = await import("@/entrypoints/content/youtube/ui/embed");
    const { rerenderEmbeds } =
        await import("@/entrypoints/content/youtube/ui/rerender");
    Settings.langCodes.subscribe(rerenderEmbeds);
    return embed;
}

async function mount(favorites: string[]) {
    const { createEmbedContainer, initEmbed } = await loadEmbed(favorites);
    const container = createEmbedContainer(VIDEO_URL);
    document.body.appendChild(container);
    await initEmbed(container, VIDEO_URL);
    return container;
}

/** The label of every badge, without the tooltip text nested inside it. */
function badgeLabels(container: HTMLElement): string[] {
    return Array.from(container.querySelectorAll(".ytbext-badge")).map((el) =>
        Array.from(el.childNodes)
            .filter((node) => node.nodeType === Node.TEXT_NODE)
            .map((node) => node.textContent)
            .join("")
            .trim(),
    );
}

beforeEach(() => {
    mocks.resolveVideoInfo.mockReset().mockResolvedValue(info);
});

describe("initEmbed", () => {
    it("shows favorite tracks in favorites order plus a count of the rest", async () => {
        const container = await mount(["fr", "en"]);

        // Captions: fr, en favorites out of en/fr/de (the auto track is
        // dropped). Audio: the original is dropped and ja is no favorite,
        // so that section shows no badges at all.
        expect(badgeLabels(container)).toEqual(["FR", "EN", "+1"]);
    });

    it("re-sorts the badges when the favorites order changes elsewhere", async () => {
        const container = await mount(["fr", "en"]);

        await fakeBrowser.storage.local.set({
            "SETTINGS:langCodes": ["en", "fr"],
        });
        await flush();

        expect(badgeLabels(container)).toEqual(["EN", "FR", "+1"]);
    });

    it("promotes a newly favorited track", async () => {
        const container = await mount([]);
        expect(badgeLabels(container)).toEqual([]);

        await fakeBrowser.storage.local.set({ "SETTINGS:langCodes": ["ja"] });
        await flush();

        expect(badgeLabels(container)).toEqual(["JA"]);
    });

    it("renders nothing when the lookup fails", async () => {
        mocks.resolveVideoInfo.mockResolvedValueOnce(null);

        const container = await mount(["en"]);

        expect(container.childElementCount).toBe(0);
    });

    it("draws nothing into a container removed while the lookup was pending", async () => {
        const { createEmbedContainer, initEmbed } = await loadEmbed(["en"]);
        let resolveLookup!: (value: VideoInfo) => void;
        mocks.resolveVideoInfo.mockReturnValueOnce(
            new Promise((resolve) => (resolveLookup = resolve)),
        );
        const container = createEmbedContainer(VIDEO_URL);
        document.body.appendChild(container);
        const done = initEmbed(container, VIDEO_URL);

        container.remove();
        resolveLookup(info);
        await done;

        expect(container.childElementCount).toBe(0);
    });

    it("tells the lookup it is no longer needed once the container is gone", async () => {
        const { createEmbedContainer, initEmbed } = await loadEmbed(["en"]);
        mocks.resolveVideoInfo.mockReturnValueOnce(new Promise(() => {}));
        const container = createEmbedContainer(VIDEO_URL);
        document.body.appendChild(container);
        void initEmbed(container, VIDEO_URL);
        const [, stillNeeded] = mocks.resolveVideoInfo.mock.calls[0]!;

        expect(stillNeeded?.()).toBe(true);
        container.remove();
        expect(stillNeeded?.()).toBe(false);
    });

    it("opens the track popup for the clicked section", async () => {
        const container = await mount(["en"]);

        container.querySelector<HTMLElement>(".ytbext-item")!.click();

        expect(
            document.querySelector(".ytbext-popup")?.getAttribute("aria-label"),
        ).toBe("Subtitle languages");
    });
});

describe("initEmbed with the language filter", () => {
    const filterSwitch = () =>
        document.querySelector<HTMLInputElement>(".ytbext-filter__input")!;
    const stateOf = (card: HTMLElement) =>
        card.getAttribute("data-ytbext-filter");
    const isHidden = (card: HTMLElement) => stateOf(card) === "hidden";

    /** Starts the filter on a search page, turned on, and mounts one card. */
    async function mountFiltered(favorites: string[]) {
        const embed = await loadEmbed(favorites);
        const filter = await import("@/entrypoints/content/youtube/filter");
        history.replaceState(null, "", "/results?search_query=x");
        document.body.innerHTML =
            '<ytd-search><div id="header" class="ytd-search"></div></ytd-search>';
        filter.startFilter();
        filterSwitch().click();

        const card = document.createElement("ytd-video-renderer");
        card.innerHTML = `<a href="/watch?v=abc"><div class="ytbext-thumbnail-wrapper"><img src="x.jpg"></div></a>`;
        document.body.appendChild(card);
        const container = embed.createEmbedContainer(VIDEO_URL);
        card.querySelector(".ytbext-thumbnail-wrapper")!.appendChild(container);
        await embed.initEmbed(container, VIDEO_URL);
        return { card, filter };
    }

    it("hides the card when the video has no favorite track", async () => {
        const { card, filter } = await mountFiltered(["ko"]);

        expect(isHidden(card)).toBe(true);
        filter.stopFilter();
    });

    it("keeps the card when the video has a favorite track", async () => {
        const { card, filter } = await mountFiltered(["fr"]);

        expect(isHidden(card)).toBe(false);
        filter.stopFilter();
    });

    it("follows a favorites change", async () => {
        const { card, filter } = await mountFiltered(["ko"]);
        expect(isHidden(card)).toBe(true);

        await fakeBrowser.storage.local.set({ "SETTINGS:langCodes": ["fr"] });
        await flush();

        expect(isHidden(card)).toBe(false);
        filter.stopFilter();
    });

    it("shows the card again when the filter is turned off", async () => {
        const { card, filter } = await mountFiltered(["ko"]);

        filterSwitch().click();

        expect(isHidden(card)).toBe(false);
        filter.stopFilter();
    });

    it("leaves the card pending until the lookup resolves, then shows an unknown video", async () => {
        const embed = await loadEmbed(["ko"]);
        const filter = await import("@/entrypoints/content/youtube/filter");
        history.replaceState(null, "", "/results?search_query=x");
        document.body.innerHTML =
            '<ytd-search><div id="header" class="ytd-search"></div></ytd-search>';
        filter.startFilter();
        filterSwitch().click();
        let resolveLookup!: (value: VideoInfo | null) => void;
        mocks.resolveVideoInfo.mockReturnValueOnce(
            new Promise((resolve) => (resolveLookup = resolve)),
        );
        // As thumbnails.ts leaves a tracked card.
        const card = document.createElement("ytd-video-renderer");
        card.setAttribute("data-ytbext-filter", "pending");
        card.innerHTML = `<a href="/watch?v=abc"><div class="ytbext-thumbnail-wrapper"><img src="x.jpg"></div></a>`;
        document.body.appendChild(card);
        const container = embed.createEmbedContainer(VIDEO_URL);
        card.querySelector(".ytbext-thumbnail-wrapper")!.appendChild(container);

        const done = embed.initEmbed(container, VIDEO_URL);
        expect(stateOf(card)).toBe("pending");

        resolveLookup(null);
        await done;

        expect(stateOf(card)).toBe("shown");
        filter.stopFilter();
    });

    it("keeps a known card's state while a further lookup in it is pending", async () => {
        const embed = await loadEmbed(["ko"]);
        const filter = await import("@/entrypoints/content/youtube/filter");
        history.replaceState(null, "", "/results?search_query=x");
        document.body.innerHTML =
            '<ytd-search><div id="header" class="ytd-search"></div></ytd-search>';
        filter.startFilter();
        filterSwitch().click();
        mocks.resolveVideoInfo.mockReturnValueOnce(new Promise(() => {}));
        // A card whose first thumbnail already resolved.
        const card = document.createElement("ytd-video-renderer");
        card.setAttribute("data-ytbext-filter", "shown");
        card.innerHTML = `<a href="/watch?v=abc"><div class="ytbext-thumbnail-wrapper"><img src="x.jpg"></div></a>`;
        document.body.appendChild(card);
        const container = embed.createEmbedContainer(VIDEO_URL);
        card.querySelector(".ytbext-thumbnail-wrapper")!.appendChild(container);

        // A second image in the same card mounts a container of its own;
        // the card is still the same video, so it must not become a
        // placeholder again.
        void embed.initEmbed(container, VIDEO_URL);

        expect(stateOf(card)).toBe("shown");
        filter.stopFilter();
    });

    it("shows a hidden card again when its container is re-initialised for an unknown video", async () => {
        const { card, filter } = await mountFiltered(["ko"]);
        expect(isHidden(card)).toBe(true);
        const { createEmbedContainer, initEmbed } =
            await import("@/entrypoints/content/youtube/ui/embed");
        mocks.resolveVideoInfo.mockResolvedValueOnce(null);

        // thumbnails.ts replaces the container when YouTube recycles the card.
        const fresh = createEmbedContainer(VIDEO_URL);
        card.querySelector(".ytbext-embed-container")!.replaceWith(fresh);
        await initEmbed(fresh, VIDEO_URL);

        expect(isHidden(card)).toBe(false);
        filter.stopFilter();
    });
});
