import type { VideoInfo } from "@/common/types";
import { describe, expect, it, vi } from "vitest";
import { fakeBrowser } from "wxt/testing/fake-browser";

const withCaption = (languageCode: string): VideoInfo => ({
    captions: [{ languageCode, name: languageCode, isAutoGenerated: false }],
    audioTracks: [],
});

/**
 * A search-result card with a mounted badge overlay, the way thumbnails.ts
 * leaves it. Returns the card and its embed container.
 */
function mountedCard(id: string): [HTMLElement, HTMLElement] {
    const card = document.createElement("ytd-video-renderer");
    card.id = id;
    card.innerHTML = `<a href="/watch?v=${id}"><div class="ytbext-thumbnail-wrapper"><img src="x.jpg"><div class="ytbext-embed-container"></div></div></a>`;
    document.body.append(card);
    return [card, card.querySelector<HTMLElement>(".ytbext-embed-container")!];
}

const STATE_ATTR = "data-ytbext-filter";
const stateOf = (card: Element) => card.getAttribute(STATE_ATTR);
const filtering = () =>
    document.documentElement.classList.contains("ytbext-filtering");

function hiddenIds(): string[] {
    return Array.from(
        document.querySelectorAll(`[${STATE_ATTR}="hidden"]`),
    ).map((el) => el.id);
}

// YouTube gives the search header a fixed height, so a row inside it would
// be covered by the results; the switch goes right after it instead.
// The headers carry Polymer's scope class (`#header.ytd-search`), which is
// what tells them apart from the `#header` divs inside result cards.
const SEARCH_HEADER =
    '<ytd-search><div id="container"><div id="header" class="style-scope ytd-search"><ytd-search-header-renderer></ytd-search-header-renderer></div><div id="primary"></div></div></ytd-search>';
const GRID_HEADER = (subtype: string) =>
    `<ytd-browse page-subtype="${subtype}"><ytd-rich-grid-renderer><div id="header" class="style-scope ytd-rich-grid-renderer"><chip-bar-view-model><div class="chips"></div></chip-bar-view-model></div></ytd-rich-grid-renderer></ytd-browse>`;
// YouTube's "Summary" box in the results has a #header of its own.
const RESULT_CARD_HEADER =
    '<ytd-expandable-metadata-renderer><div id="header" class="style-scope ytd-expandable-metadata-renderer"></div></ytd-expandable-metadata-renderer>';

const control = () => document.querySelector<HTMLElement>(".ytbext-filter");
const switchInput = () =>
    document.querySelector<HTMLInputElement>(".ytbext-filter__input");
const toggleSwitch = () => switchInput()!.click();

async function loadFilter(
    favorites: string[],
    { path = "/results?search_query=x", page = SEARCH_HEADER } = {},
) {
    fakeBrowser.reset();
    await fakeBrowser.storage.local.set({ "SETTINGS:langCodes": favorites });
    document.body.innerHTML = page;
    vi.resetModules();
    const { Settings } = await import("@/common/settings");
    await Settings.ready();
    const filter = await import("@/entrypoints/content/youtube/filter");
    history.replaceState(null, "", path);
    filter.startFilter();
    return filter;
}

describe("filterable pages", () => {
    // Both headers on the page, so only the path decides.
    const BOTH_HEADERS = SEARCH_HEADER + GRID_HEADER("channels");

    it.each([
        "/results",
        "/@handle/videos",
        "/channel/UCabc123/videos",
        "/c/SomeName/videos",
        "/user/someone/videos",
    ])("mounts the switch on %s", async (path) => {
        const { stopFilter } = await loadFilter([], {
            path,
            page: BOTH_HEADERS,
        });
        expect(control()).not.toBeNull();
        stopFilter();
    });

    it.each([
        "/",
        "/watch",
        "/@handle",
        "/@handle/shorts",
        "/@handle/streams",
        "/@handle/videos/extra",
        "/feed/subscriptions",
    ])("leaves %s alone", async (path) => {
        const { stopFilter } = await loadFilter([], {
            path,
            page: BOTH_HEADERS,
        });
        expect(control()).toBeNull();
        stopFilter();
    });
});

describe("mounting the switch", () => {
    it("adds a row right after the search header, switched off", async () => {
        const { stopFilter } = await loadFilter(["en"]);

        // A block-level wrapper carries the header's max-width and centring;
        // the label inside it stays compact.
        const host = document.querySelector("ytd-search #header + *")!;
        expect(host.classList.contains("ytbext-filter-host--row")).toBe(true);
        expect(host.firstElementChild).toBe(control());
        expect(switchInput()!.checked).toBe(false);
        expect(switchInput()!.getAttribute("role")).toBe("switch");
        expect(control()!.textContent).toContain("Only show my languages");
        expect(control()!.title).toMatch(/your languages/);
        expect(control()!.querySelector("svg")).not.toBeNull();
        stopFilter();
    });

    it("adds to the chip bar on a channel Videos tab", async () => {
        const { stopFilter } = await loadFilter(["en"], {
            path: "/@handle/videos",
            page: GRID_HEADER("channels"),
        });

        const host = document.querySelector(
            "chip-bar-view-model > :last-child",
        )!;
        expect(host.classList.contains("ytbext-filter-host--inline")).toBe(
            true,
        );
        expect(host.firstElementChild).toBe(control());
        stopFilter();
    });

    it("leaves the home feed's grid alone", async () => {
        const { stopFilter } = await loadFilter(["en"], {
            path: "/",
            page: GRID_HEADER("home"),
        });

        expect(control()).toBeNull();
        stopFilter();
    });

    it("mounts once the header shows up later, and only once", async () => {
        const { mountFilterIn, stopFilter } = await loadFilter(["en"], {
            page: "",
        });
        expect(control()).toBeNull();

        document.body.innerHTML = SEARCH_HEADER;
        const header =
            document.querySelector<HTMLElement>("ytd-search #header")!;
        mountFilterIn(header);
        mountFilterIn(header);
        mountFilterIn(document);

        expect(document.querySelectorAll(".ytbext-filter")).toHaveLength(1);
        stopFilter();
    });

    it("mounts from an element added inside the chip bar", async () => {
        const { mountFilterIn, stopFilter } = await loadFilter(["en"], {
            path: "/@handle/videos",
            page: "",
        });
        document.body.innerHTML = GRID_HEADER("channels");
        const chips = document.querySelector<HTMLElement>(".chips")!;

        mountFilterIn(chips);

        expect(control()).not.toBeNull();
        expect(control()!.closest("chip-bar-view-model")).not.toBeNull();
        stopFilter();
    });

    it("moves to a header that replaces the one it was in", async () => {
        const { mountFilterIn, stopFilter } = await loadFilter(["en"]);
        const old = document.querySelector<HTMLElement>("ytd-search #header")!;
        expect(control()).not.toBeNull();

        // YouTube inserts the new header before dropping the old one.
        const fresh = old.cloneNode(false) as HTMLElement;
        old.after(fresh);
        mountFilterIn(fresh);
        old.remove();

        expect(document.querySelectorAll(".ytbext-filter")).toHaveLength(1);
        expect(control()!.parentElement!.previousElementSibling).toBe(fresh);
        stopFilter();
    });

    it("does not move into a result card's own #header", async () => {
        const { mountFilterIn, stopFilter } = await loadFilter(["en"]);
        const primary = document.querySelector("#primary")!;
        primary.innerHTML = RESULT_CARD_HEADER;

        mountFilterIn(primary.querySelector("#header")!);

        expect(document.querySelectorAll(".ytbext-filter")).toHaveLength(1);
        expect(
            control()!.parentElement!.previousElementSibling!.classList.contains(
                "ytd-search",
            ),
        ).toBe(true);
        stopFilter();
    });

    it("ignores headers while stopped", async () => {
        const { mountFilterIn, stopFilter } = await loadFilter(["en"]);
        stopFilter();
        document.body.innerHTML = SEARCH_HEADER;

        mountFilterIn(document);

        expect(control()).toBeNull();
    });

    it("is removed on stop", async () => {
        const { stopFilter } = await loadFilter(["en"]);
        expect(control()).not.toBeNull();

        stopFilter();

        expect(control()).toBeNull();
    });

    it("follows YouTube's SPA navigation", async () => {
        const { stopFilter } = await loadFilter(["en"]);
        expect(control()).not.toBeNull();

        // Leaving the results page: YouTube swaps the page element out.
        document.body.innerHTML = GRID_HEADER("home");
        history.replaceState(null, "", "/");
        document.dispatchEvent(new Event("yt-navigate-finish"));
        expect(control()).toBeNull();

        // A channel tab reuses ytd-browse; the header is already in place.
        document
            .querySelector("ytd-browse")!
            .setAttribute("page-subtype", "channels");
        history.replaceState(null, "", "/@handle/videos");
        document.dispatchEvent(new Event("yt-navigate-finish"));
        expect(control()).not.toBeNull();

        // Back home with the same grid: the control must go away.
        history.replaceState(null, "", "/");
        document.dispatchEvent(new Event("yt-navigate-finish"));
        expect(control()).toBeNull();
        stopFilter();
    });

    it("toggles between on and off", async () => {
        const { stopFilter } = await loadFilter(["en"]);

        toggleSwitch();
        expect(switchInput()!.checked).toBe(true);
        toggleSwitch();
        expect(switchInput()!.checked).toBe(false);
        stopFilter();
    });

    it("asks every embed to re-render when toggled", async () => {
        const { stopFilter } = await loadFilter(["en"]);
        const [, container] = mountedCard("fr1");
        let renders = 0;
        container.addEventListener("ytbext:render", () => renders++);

        toggleSwitch();
        toggleSwitch();

        expect(renders).toBe(2);
        stopFilter();
    });
});

describe("applyCardFilter", () => {
    it("hides the card while the filter is on and the video has no favorite track", async () => {
        const { applyCardFilter, stopFilter } = await loadFilter(["en"]);
        const [, en] = mountedCard("en1");
        const [, fr] = mountedCard("fr2");
        toggleSwitch();

        applyCardFilter(en, withCaption("en"));
        applyCardFilter(fr, withCaption("fr"));

        expect(hiddenIds()).toEqual(["fr2"]);
        stopFilter();
    });

    it("marks the card shown while the filter is off", async () => {
        const { applyCardFilter, stopFilter } = await loadFilter(["en"]);
        const [card, fr] = mountedCard("fr1");

        applyCardFilter(fr, withCaption("fr"));

        expect(stateOf(card)).toBe("shown");
        stopFilter();
    });

    it("shows the card when the video is unknown", async () => {
        const { applyCardFilter, stopFilter } = await loadFilter(["en"]);
        const [card, fr] = mountedCard("fr1");
        toggleSwitch();
        applyCardFilter(fr, withCaption("fr"));
        expect(stateOf(card)).toBe("hidden");

        applyCardFilter(fr, null);

        expect(stateOf(card)).toBe("shown");
        stopFilter();
    });

    it("clearCardFilter puts the card back to pending", async () => {
        const { applyCardFilter, clearCardFilter, stopFilter } =
            await loadFilter(["en"]);
        const [card, fr] = mountedCard("fr1");
        toggleSwitch();
        applyCardFilter(fr, withCaption("fr"));

        clearCardFilter(fr);

        expect(stateOf(card)).toBe("pending");
        stopFilter();
    });

    it("markCardPending marks the card around a thumbnail", async () => {
        const { markCardPending, stopFilter } = await loadFilter(["en"]);
        const [card] = mountedCard("fr1");

        markCardPending(card.querySelector("img")!);

        expect(stateOf(card)).toBe("pending");
        stopFilter();
    });

    it("markCardPending leaves an element outside any card alone", async () => {
        const { markCardPending, stopFilter } = await loadFilter(["en"]);
        const img = document.createElement("img");
        document.body.append(img);

        expect(() => markCardPending(img)).not.toThrow();
        expect(document.querySelector(`[${STATE_ATTR}]`)).toBeNull();
        stopFilter();
    });

    it("marks the page as filtering only while the switch is on", async () => {
        const { stopFilter } = await loadFilter(["en"]);
        expect(filtering()).toBe(false);

        toggleSwitch();
        expect(filtering()).toBe(true);

        toggleSwitch();
        expect(filtering()).toBe(false);
        stopFilter();
    });

    it("hides the outer card when a lockup is nested in a grid item", async () => {
        const { applyCardFilter, stopFilter } = await loadFilter(["en"]);
        const outer = document.createElement("ytd-rich-item-renderer");
        outer.id = "outer";
        outer.innerHTML =
            '<yt-lockup-view-model id="inner"><a href="/watch?v=fr1"><div class="ytbext-thumbnail-wrapper"><img src="x.jpg"><div class="ytbext-embed-container"></div></div></a></yt-lockup-view-model>';
        document.body.append(outer);
        toggleSwitch();

        applyCardFilter(
            outer.querySelector<HTMLElement>(".ytbext-embed-container")!,
            withCaption("fr"),
        );

        expect(hiddenIds()).toEqual(["outer"]);
        stopFilter();
    });
});

describe("the hidden count", () => {
    const count = () => document.querySelector(".ytbext-filter__count");
    // The count is refreshed once per microtask, not on every card.
    const flush = () => Promise.resolve();

    it("says how many cards are hidden", async () => {
        const { applyCardFilter, stopFilter } = await loadFilter(["en"]);
        const [, en] = mountedCard("en1");
        const [, fr] = mountedCard("fr2");
        const [, de] = mountedCard("de3");
        toggleSwitch();

        applyCardFilter(en, withCaption("en"));
        applyCardFilter(fr, withCaption("fr"));
        applyCardFilter(de, withCaption("de"));
        await flush();

        expect(count()!.textContent.trim()).toBe("2 hidden");
        stopFilter();
    });

    it("says 0 hidden while on with nothing hidden, and is empty while off", async () => {
        const { applyCardFilter, stopFilter } = await loadFilter(["en"]);
        const [, en] = mountedCard("en1");
        // The span is always there, so it is a live region before its first
        // announcement; it has text only while the switch is on.
        expect(count()!.textContent.trim()).toBe("");

        toggleSwitch();
        applyCardFilter(en, withCaption("en"));
        await flush();

        expect(count()!.textContent.trim()).toBe("0 hidden");
        stopFilter();
    });

    it("empties when the filter is turned off", async () => {
        const { applyCardFilter, stopFilter } = await loadFilter(["en"]);
        const [, fr] = mountedCard("fr1");
        toggleSwitch();
        applyCardFilter(fr, withCaption("fr"));
        await flush();
        expect(count()!.textContent.trim()).toBe("1 hidden");

        toggleSwitch();
        await flush();

        expect(count()!.textContent.trim()).toBe("");
        stopFilter();
    });

    it("starts from 0 hidden when turned on again", async () => {
        const { applyCardFilter, stopFilter } = await loadFilter(["en"]);
        const [, fr] = mountedCard("fr1");
        toggleSwitch();
        applyCardFilter(fr, withCaption("fr"));
        await flush();
        expect(count()!.textContent.trim()).toBe("1 hidden");

        // Off and on again with no pause in between: the old number must not
        // show until the recount catches up.
        toggleSwitch();
        toggleSwitch();

        expect(count()!.textContent.trim()).toBe("0 hidden");
        stopFilter();
    });

    it("does not scan the page while the filter is off", async () => {
        const { applyCardFilter, stopFilter } = await loadFilter(["en"]);
        const [, fr] = mountedCard("fr1");
        const querySelectorAll = vi.spyOn(document, "querySelectorAll");

        applyCardFilter(fr, withCaption("fr"));
        await flush();

        expect(
            querySelectorAll.mock.calls.map(([selector]) => selector),
        ).not.toContain(`[${STATE_ATTR}="hidden"]`);
        querySelectorAll.mockRestore();
        stopFilter();
    });
});

describe("restoring cards", () => {
    async function hideOne() {
        const filter = await loadFilter(["en"]);
        const [, fr] = mountedCard("fr1");
        toggleSwitch();
        filter.applyCardFilter(fr, withCaption("fr"));
        expect(hiddenIds()).toEqual(["fr1"]);
        return filter;
    }

    // Off keeps the "shown" marks: a card whose lookup failed has no render
    // listener, so an unmarked card would stay a placeholder next time.
    it("marks every hidden card shown when the filter is turned off", async () => {
        const { stopFilter } = await hideOne();

        toggleSwitch();

        expect(stateOf(document.getElementById("fr1")!)).toBe("shown");
        expect(filtering()).toBe(false);
        stopFilter();
    });

    it("turns the filter off and shows every card on navigation", async () => {
        const { stopFilter } = await hideOne();

        document.dispatchEvent(new Event("yt-navigate-finish"));

        expect(hiddenIds()).toEqual([]);
        expect(filtering()).toBe(false);
        expect(switchInput()!.checked).toBe(false);
        stopFilter();
    });

    it("strips every mark on stop, pending included", async () => {
        const { markCardPending, stopFilter } = await hideOne();
        const [pending] = mountedCard("en2");
        markCardPending(pending.querySelector("img")!);
        expect(stateOf(pending)).toBe("pending");

        stopFilter();

        expect(document.querySelector(`[${STATE_ATTR}]`)).toBeNull();
        expect(filtering()).toBe(false);
    });
});
