import type { CaptionTrack, VideoInfo } from "@/common/types";
import {
    hasFavoriteTrack,
    sortByFavorite,
} from "@/entrypoints/content/youtube/tracks";
import { describe, expect, it } from "vitest";

const track = (languageCode: string): CaptionTrack => ({
    languageCode,
    name: languageCode,
    isAutoGenerated: false,
});
const codes = (tracks: CaptionTrack[]) => tracks.map((t) => t.languageCode);

describe("sortByFavorite", () => {
    it("puts favorites first in favorites order and keeps the rest in place", () => {
        const tracks = ["de", "en", "ja", "fr", "es"].map(track);

        expect(codes(sortByFavorite(tracks, ["fr", "en"]))).toEqual([
            "fr",
            "en",
            "de",
            "ja",
            "es",
        ]);
    });

    it("leaves the order alone when nothing is a favorite", () => {
        const tracks = ["de", "en", "ja"].map(track);

        expect(codes(sortByFavorite(tracks, ["zz"]))).toEqual([
            "de",
            "en",
            "ja",
        ]);
    });

    it("does not mutate its input", () => {
        const tracks = ["de", "en"].map(track);

        sortByFavorite(tracks, ["en"]);

        expect(codes(tracks)).toEqual(["de", "en"]);
    });
});

describe("hasFavoriteTrack", () => {
    const info = (
        captions: [code: string, auto: boolean][],
        audio: [code: string, original: boolean][],
    ): VideoInfo => ({
        captions: captions.map(([languageCode, isAutoGenerated]) => ({
            languageCode,
            name: languageCode,
            isAutoGenerated,
        })),
        audioTracks: audio.map(([languageCode, isOriginal]) => ({
            languageCode,
            name: languageCode,
            isOriginal,
        })),
    });

    it("matches a human caption in a favorite language", () => {
        expect(hasFavoriteTrack(info([["fr", false]], []), ["en", "fr"])).toBe(
            true,
        );
    });

    it("matches a dub in a favorite language", () => {
        expect(hasFavoriteTrack(info([], [["en", false]]), ["en"])).toBe(true);
    });

    it("ignores auto-generated captions and the original audio", () => {
        const video = info([["en", true]], [["en", true]]);

        expect(hasFavoriteTrack(video, ["en"])).toBe(false);
    });

    it("is false when no track is a favorite", () => {
        const video = info([["de", false]], [["ja", false]]);

        expect(hasFavoriteTrack(video, ["en"])).toBe(false);
    });
});
