// https://www.youtube.com/account_playback
// https://www.youtube.com/youtubei/v1/get_panel

export const LANG_CODES: Record<string, string> = {
    ab: "Abkhazian",
    aa: "Afar",
    af: "Afrikaans",
    ak: "Akan",
    akk: "Akkadian",
    sq: "Albanian",
    ase: "American Sign Language",
    am: "Amharic",
    ar: "Arabic",
    arc: "Aramaic",
    hy: "Armenian",
    as: "Assamese",
    ay: "Aymara",
    az: "Azerbaijani",
    bm: "Bambara",
    bn: "Bangla",
    "bn-IN": "Bangla (India)",
    ba: "Bashkir",
    eu: "Basque",
    be: "Belarusian",
    bh: "Bhojpuri",
    bi: "Bislama",
    brx: "Bodo",
    bs: "Bosnian",
    br: "Breton",
    bg: "Bulgarian",
    my: "Burmese",
    yue: "Cantonese",
    "yue-HK": "Cantonese (Hong Kong)",
    ca: "Catalan",
    chr: "Cherokee",
    zh: "Chinese",
    "zh-CN": "Chinese (China)",
    "zh-HK": "Chinese (Hong Kong)",
    "zh-Hans": "Chinese (Simplified)",
    "zh-SG": "Chinese (Singapore)",
    "zh-TW": "Chinese (Taiwan)",
    "zh-Hant": "Chinese (Traditional)",
    cho: "Choctaw",
    cop: "Coptic",
    co: "Corsican",
    cr: "Cree",
    hr: "Croatian",
    cs: "Czech",
    da: "Danish",
    doi: "Dogri",
    nl: "Dutch",
    "nl-BE": "Dutch (Belgium)",
    "nl-NL": "Dutch (Netherlands)",
    dz: "Dzongkha",
    en: "English",
    "en-AU": "English (Australia)",
    "en-CA": "English (Canada)",
    "en-IN": "English (India)",
    "en-IE": "English (Ireland)",
    "en-GB": "English (United Kingdom)",
    "en-US": "English (United States)",
    eo: "Esperanto",
    et: "Estonian",
    ee: "Ewe",
    fo: "Faroese",
    fj: "Fijian",
    fil: "Filipino",
    fi: "Finnish",
    fr: "French",
    "fr-BE": "French (Belgium)",
    "fr-CA": "French (Canada)",
    "fr-FR": "French (France)",
    "fr-CH": "French (Switzerland)",
    ff: "Fula",
    gl: "Galician",
    lg: "Ganda",
    ka: "Georgian",
    de: "German",
    "de-AT": "German (Austria)",
    "de-DE": "German (Germany)",
    "de-CH": "German (Switzerland)",
    el: "Greek",
    gn: "Guarani",
    gu: "Gujarati",
    guz: "Gusii",
    ht: "Haitian Creole",
    hak: "Hakka Chinese",
    "hak-TW": "Hakka Chinese (Taiwan)",
    bgc: "Haryanvi",
    ha: "Hausa",
    haw: "Hawaiian",
    iw: "Hebrew",
    hi: "Hindi",
    "hi-Latn": "Hindi (Latin)",
    ho: "Hiri Motu",
    hu: "Hungarian",
    is: "Icelandic",
    ig: "Igbo",
    id: "Indonesian",
    ia: "Interlingua",
    ie: "Interlingue",
    iu: "Inuktitut",
    ik: "Inupiaq",
    ga: "Irish",
    it: "Italian",
    ja: "Japanese",
    jv: "Javanese",
    kl: "Kalaallisut",
    kln: "Kalenjin",
    kam: "Kamba",
    kn: "Kannada",
    ks: "Kashmiri",
    kk: "Kazakh",
    km: "Khmer",
    ki: "Kikuyu",
    rw: "Kinyarwanda",
    tlh: "Klingon",
    kok: "Konkani",
    ko: "Korean",
    ku: "Kurdish",
    ky: "Kyrgyz",
    lad: "Ladino",
    lo: "Lao",
    la: "Latin",
    lv: "Latvian",
    ln: "Lingala",
    lt: "Lithuanian",
    dsb: "Lower Sorbian",
    lu: "Luba-Katanga",
    luo: "Luo",
    lb: "Luxembourgish",
    luy: "Luyia",
    mk: "Macedonian",
    mai: "Maithili",
    mg: "Malagasy",
    ms: "Malay",
    "ms-SG": "Malay (Singapore)",
    ml: "Malayalam",
    mt: "Maltese",
    mni: "Manipuri",
    mi: "Māori",
    mr: "Marathi",
    mas: "Masai",
    mer: "Meru",
    nan: "Min Nan Chinese",
    "nan-TW": "Min Nan Chinese (Taiwan)",
    mxp: "Mixe",
    lus: "Mizo",
    mn: "Mongolian",
    "mn-Mong": "Mongolian (Mongolian)",
    na: "Nauru",
    nv: "Navajo",
    ne: "Nepali",
    pcm: "Nigerian Pidgin",
    nd: "North Ndebele",
    nso: "Northern Sotho",
    no: "Norwegian",
    oc: "Occitan",
    or: "Odia",
    om: "Oromo",
    pap: "Papiamento",
    ps: "Pashto",
    fa: "Persian",
    "fa-AF": "Persian (Afghanistan)",
    "fa-IR": "Persian (Iran)",
    pl: "Polish",
    pt: "Portuguese",
    "pt-BR": "Portuguese (Brazil)",
    "pt-PT": "Portuguese (Portugal)",
    pa: "Punjabi",
    qu: "Quechua",
    ro: "Romanian",
    mo: "Romanian (Moldova)",
    rm: "Romansh",
    rn: "Rundi",
    ru: "Russian",
    "ru-Latn": "Russian (Latin)",
    sm: "Samoan",
    sg: "Sango",
    sa: "Sanskrit",
    sat: "Santali",
    sc: "Sardinian",
    gd: "Scottish Gaelic",
    sr: "Serbian",
    "sr-Cyrl": "Serbian (Cyrillic)",
    "sr-Latn": "Serbian (Latin)",
    sh: "Serbo-Croatian",
    sdp: "Sherdukpen",
    sn: "Shona",
    scn: "Sicilian",
    sd: "Sindhi",
    si: "Sinhala",
    sk: "Slovak",
    sl: "Slovenian",
    so: "Somali",
    nr: "South Ndebele",
    st: "Southern Sotho",
    es: "Spanish",
    "es-419": "Spanish (Latin America)",
    "es-MX": "Spanish (Mexico)",
    "es-ES": "Spanish (Spain)",
    "es-US": "Spanish (United States)",
    su: "Sundanese",
    sw: "Swahili",
    ss: "Swati",
    sv: "Swedish",
    tl: "Tagalog",
    tg: "Tajik",
    ta: "Tamil",
    tt: "Tatar",
    te: "Telugu",
    th: "Thai",
    bo: "Tibetan",
    ti: "Tigrinya",
    tpi: "Tok Pisin",
    tok: "Toki Pona",
    to: "Tongan",
    ts: "Tsonga",
    tn: "Tswana",
    tr: "Turkish",
    tk: "Turkmen",
    tw: "Twi",
    uk: "Ukrainian",
    hsb: "Upper Sorbian",
    ur: "Urdu",
    ug: "Uyghur",
    uz: "Uzbek",
    ve: "Venda",
    vi: "Vietnamese",
    vo: "Volapük",
    vro: "Võro",
    wa: "Walloon",
    cy: "Welsh",
    fy: "Western Frisian",
    wal: "Wolaytta",
    wo: "Wolof",
    xh: "Xhosa",
    yi: "Yiddish",
    yo: "Yoruba",
    zu: "Zulu",
};
