/**
 * IndexedDB cache of video info, owned by the background script.
 */
import { IDBStore } from "./idb";
import type { CacheEntry, VideoInfo } from "./types";

/** How long a lookup result stays valid. Cache timestamps are in seconds. */
export const CACHE_TTL_SECONDS = 60 * 30;

const nowSeconds = () => Date.now() / 1000;

class VideoCache {
    // Version 2: the track flags were renamed (isAutoGenerated, isOriginal),
    // and the bump drops the entries written under the old names.
    private store = new IDBStore<CacheEntry>(
        "subpeek-video-cache",
        "videoInfo",
        2,
        {
            keyPath: "videoId",
            indexes: [{ name: "timestamp", keyPath: "timestamp" }],
        },
    );

    /** The cached info for `videoId`; null when absent or older than the TTL. */
    async get(videoId: string): Promise<VideoInfo | null> {
        try {
            const entry = await this.store.get(videoId);
            if (!entry || nowSeconds() - entry.timestamp >= CACHE_TTL_SECONDS) {
                return null;
            }
            return entry.data;
        } catch (error) {
            logger.error("VideoCache.get error:", error);
            return null;
        }
    }

    async set(videoId: string, data: VideoInfo): Promise<void> {
        try {
            await this.store.put({ videoId, data, timestamp: nowSeconds() });
        } catch (error) {
            logger.error("VideoCache.set error:", error);
        }
    }

    /** Drops expired entries. get() never returns them, so this is only housekeeping. */
    async cleanExpired(): Promise<void> {
        try {
            await this.store.deleteByIndexRange(
                "timestamp",
                IDBKeyRange.upperBound(nowSeconds() - CACHE_TTL_SECONDS),
            );
        } catch (error) {
            logger.error("VideoCache.cleanExpired error:", error);
        }
    }
}

/** Singleton cache instance */
export const videoCache = new VideoCache();
