export interface CaptionTrack {
    languageCode: string;
    name: string;
    /** Speech-recognition captions generated by YouTube rather than a person. */
    isAutoGenerated: boolean;
}

export interface AudioTrack {
    languageCode: string;
    name: string;
    /** The video's original audio, as opposed to a dub. */
    isOriginal: boolean;
}

/** Everything SubPeek knows about one video. */
export interface VideoInfo {
    captions: CaptionTrack[];
    audioTracks: AudioTrack[];
}

/** One IndexedDB record of the video cache; `timestamp` is in seconds. */
export interface CacheEntry {
    videoId: string;
    data: VideoInfo;
    timestamp: number;
}

export type TrackItem = CaptionTrack | AudioTrack;
